name: Test

on: [ push, pull_request ]

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - name: Build all
      run: nix-build all.nix

